### ISSUE TITLE
Unity GameObject desplay wrong.

### ISSUE THREAD

**Issue by Tengpaz** [BUAA-Soft-2024-Summer/Soft-Summer-2024#2]
# Unity游戏对象显示Bug

## 环境工具

- Unity 2022.3.35f1 模板2D(Built-In Render Pipeline)
- Windows11
- Visual Studio 2022

## 问题阐述

![image](https://github.com/user-attachments/assets/1a95e5ef-32fc-4101-bf78-2387ad293bbd)

如图`GameObject EndBed`子物体`DownArrow`初始未运行时为禁用状态

![image](https://github.com/user-attachments/assets/7a9143e9-001c-4003-940f-1ff57349dda3)

同时子物体`Bed`中的代码`End`和`Notify Script Component`均初始时为禁用状态

运行预期效果为角色接触床`EndBed`物体后上方不会显示提示箭头`DownArrow`

### 实际运行图片

**物体接触`EndBed`物体时**

![image](https://github.com/user-attachments/assets/336256a7-cd8f-43d6-8263-faed4f02a353)

此时`Hierarchy`栏内`DownArrow`物体变为`Active`状态

**物体离开`EndBed`物体时**

![image](https://github.com/user-attachments/assets/c9c6dfb9-1528-4b93-b0ed-593269eb4d48)

此时`Hierarchy`栏内`DownArrow`物体变为`Not Active`即禁用状态

### 补充信息

![image](https://github.com/user-attachments/assets/ceac8030-a16c-4037-9485-77e3b15fce36)

图示物体`DownArrow`物体的`Inspector`栏信息

```C#
using System.Collections;
using System.Collections.Generic;
using Unity.VisualScripting;
using UnityEngine;

public class Notify : MonoBehaviour
{
    [SerializeField] private GameObject Arrow;

    private void Start()
    {
        Arrow.SetActive(false);
    }

    private void OnTriggerEnter2D(Collider2D collision)
    {
        if (collision.CompareTag("Player"))
        {
            Arrow.SetActive(true);
        }
    }

    private void OnTriggerExit2D(Collider2D collision)
    {
        if (collision.CompareTag("Player"))
        {
            Arrow.SetActive(false);
        }
    }
}
```
此为代码`Notify`代码内容

```C#
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;

public class End : MonoBehaviour
{
    [SerializeField] private GameObject Player;

    private bool InBed = false;
    private Animator animator;
    private string[] worldName = { "Menu", "Green", "White", "Red", "MainScene" };


    private void Start()
    {
        gameObject.GetComponent<End>().enabled = false;
        animator = GetComponent<Animator>();
    }

    private void OnTriggerEnter2D(Collider2D collision)
    {
        if (collision.CompareTag("Player"))
        {
            InBed = true;
        }
    }

    private void OnTriggerExit2D(Collider2D collision)
    {
        if (collision.CompareTag("Player"))
        {
            InBed = false;
        }
    }

    private void Update()
    {
        if (InBed)
        {
            if (Input.GetKeyUp("down") && Player.activeInHierarchy == true)
            {
                FallAsleep();
            }
        }
    }

    private void FallAsleep()
    {
        Player.SetActive(false);
        transform.parent.GetChild(1).gameObject.SetActive(false);
        animator.SetBool("IsSleep", true);
    }

    private void transfer()
    {
        SceneManager.LoadScene(4);
    }
}
```
此为代码`End`的代码内容

## 解决需求

使得无论角色是否触碰物体`EndBed`，上方箭头初始时都不会`Active`

**Comment by Tengpaz** [comment]
# 补充信息

图片所示两状态下组件`Notify`均为`Not Enable`状态

**Comment by Ferpakenameyea** [comment]
我很抱歉，不过这个问题的描述以及代码看起来实在让人困惑，如果您只是需要一个指引箭头，您应当只是书写一个类来直接控制`Arrow`是否为`Active`。

如果您的需求仅仅是让箭头初始时不会`Active`，你可以在控制显示的类中加入判断玩家是否有离开过碰撞箱，如果玩家从未离开碰撞箱，就不要让自己显示。或者在初始状态下不要让玩家和碰撞箱重叠。

并且我建议您重构一下自己的代码，现在的显示逻辑有些过于紧耦且复杂。

很抱歉我不能完全解决您的问题。如果您需要更多帮助，可以单独联系我。

**Comment by Ferpakenameyea** [comment]
对于简单的碰撞箱重叠检测，您可以使用如下代码的方法：

```C#
void CheckBoundsOverlap(Collider otherCollider)
{
    Collider myCollider = GetComponent<Collider>();
    
    if (myCollider.bounds.Intersects(otherCollider.bounds))
    {
        // Do something...
        Debug.Log("Bounds overlap with " + otherCollider.gameObject.name);
    }
}

```

**Comment by Tengpaz** [comment]
感谢学长提供的代码！碰撞箱重叠目前还不会所以处理比较复杂www还有问题我单独找学长您，谢谢助教！！
